import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";;
import "./globals.css";


const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}  >
      <body
      className="bg-gradient-to-br from-indigo-50 via-white to-purple-100 min-h-screen"
      
      >
        {children}
      </body>
    </html>
  );
}
